### ISSUE TITLE
[Bug] 已解决 镜像的系统时间不对，比北京时间晚了8h

### ISSUE THREAD

**Issue by adgad2** [0-8-4/miui-auto-tasks#129]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

v1.6.0.1

### Bug Found in Environment

Windows

### Bug Found in Python Version

3.9

### Describe the Bug

rt，使用自己写的docker-compose启动，发现时间不对，实际比北京时间晚了8小时，如果不是bug希望可以在wiki上注明

自己在docker-compose里加上环境变量后已解决

`
version: '3'
services:
  miui-auto-tasks:
    image: o1si/miui-auto-tasks:latest
    volumes:
      - ./config.yaml:/srv/config.yaml
      - ./crontab:/var/spool/cron/crontabs/root
    environment:
      - TZ=Asia/Shanghai
`

### MIUITask Log

无

**Comment by adgad2** [comment]
```
version: '3'
services:
  miui-auto-tasks:
    image: o1si/miui-auto-tasks:latest
    volumes:
      - ./config.yaml:/srv/config.yaml
      - ./crontab:/var/spool/cron/crontabs/root
    environment:
      - TZ=Asia/Shanghai
```
